### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/carlos.cifuentes/Laboratorio/M...

### ISSUE THREAD

**Issue by beeva-carloscifuentes** [tomkadwill/atom-cucumber-autocomplete#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.1
**Thrown From**: [cucumber-autocomplete](https://github.com/tomkadwill/atom-cucumber-autocomplete) package, v0.2.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/carlos.cifuentes/Laboratorio/MooM/buzz-moomt/features'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir '/Users/carlos.cifuentes/Laboratorio/MooM/buzz-moomt/features'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.module.exports.getCompletions (/Users/carlos.cifuentes/.atom/packages/cucumber-autocomplete/lib/provider.coffee:28:5)
    at Object.module.exports.getSuggestions (/Users/carlos.cifuentes/.atom/packages/cucumber-autocomplete/lib/provider.coffee:16:6)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -9:07.9.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
     -9:06.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:10.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:10.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -3:09.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:03.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -3:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:25.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
  3x -0:33.8.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:02.2.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
cucumber, v0.5.0
cucumber-autocomplete, v0.2.0
language-gherkin, v1.0.3
language-ini, v1.14.0

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @beeva-carloscifuentes 
This does look like a bug. Where is your feature directory for this project?

**Comment by beeva-carloscifuentes** [comment]
Hi @_tomkadwill https://github.com/tomkadwill_!

We have a custom directory structure:
- features/
  -- login/_.features
  -- home/_.features
- impl/
  -- helpers/...
  -- screens/...
  -- step_definitions/...
  -- support/...

Could it be possible, in the plugin configuration, could set the path of
the files necessary for the autocomplete?

Thanks!

2016-02-01 12:08 GMT+01:00 Tom Kadwill notifications@github.com:

> Hi @beeva-carloscifuentes https://github.com/beeva-carloscifuentes
> This does look like a bug. Where is your feature directory for this
> project?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomkadwill/atom-cucumber-autocomplete/issues/1#issuecomment-177917314
> .

## 

_CARLOS CIFUENTES FERNÁNDEZ_
_JEFE DE PROYECTO_
_+34 620 975 234 / carlos.cifuentes@bbva.com carlos.cifuentes@bbva.com
carlos.cifuentes@beeva.com carlos.cifuentes@beeva.com_

Aviso Legal:
Este mensaje, su contenido y cualquier fichero transmitido con él, está
dirigido únicamente a su destinatario y es confidencial. Por ello, se
informa a quien lo reciba por error o tenga conocimiento del mismo sin ser
su destinatario, que la información contenida en él es reservada y su uso
no autorizado, por lo que en tal caso le rogamos nos lo comunique por la
misma vía, así como que se abstenga de reproducir el mensaje mediante
cualquier medio o remitirlo o entregarlo a otra persona, procediendo a su
borrado de manera inmediata.

Disclaimer:
This message, its content and any file attached thereto is for the intended
recipient only and is confidential. If you have received this e-mail in
error or had access to it, you should note that the information in it is
private and any use thereof is unauthorized. In such an event please notify
us by e-mail. Any reproduction of this e-mail by whatsoever means and any
transmission or dissemination thereof to other persons is prohibited. It
should be deleted immediately from your system.

**Comment by beeva-carloscifuentes** [comment]
Hi @tomkadwill!

We have a custom directory structure:
- features/login/*.features
- features/home/*.features
- impl/helpers/...
- impl/screens/...
- impl/step_definitions/...
- impl/support/...

Could it be possible, in the plugin configuration, could set the path of the files necessary for the autocomplete?

Thanks!

**Comment by tomkadwill** [comment]
Sure! That's something I'd like to add. I'm hoping to find time in the next few weeks. 

If you need it sooner than please feel free to make a PR and i'll get it merged quickly for you :)

**Comment by beeva-carloscifuentes** [comment]
Thank you very much for the effort! :-)

**Comment by tomkadwill** [comment]
Hi @beeva-carloscifuentes, I've added a configuration option which will allow you to specify the directory of your feature files. I don't think it solves all your problems but it is a start. If you go into the package settings and set the path to `features/login` (for example), does it work for you?

**Comment by tomkadwill** [comment]
Closing this issue. Please re-open if this is still a problem
