### ISSUE TITLE
Recursively Scan Features Directory

### ISSUE THREAD

**Issue by Ellisande** [tomkadwill/atom-cucumber-autocomplete#11]
My current project structure is: `test => features => epicFeature => severalFeatureFiles`, but when I provide the the `test/features` path to the plugin it only looks for `.feature` files directly in the `features` folder. It would be really useful if it scanned any feature files under the root directory.

Not sure if this is a bug for using a custom feature folder path, or an enhancement, but either way it would be really helpful. If you like the suggestion I'd be happy to do a pull request for it.

Thanks

**Comment by tomkadwill** [comment]
Hi @Ellisande, thanks for raising this. That sounds like a great addition to this package. Please go ahead and submit a pull request :)

**Comment by tomkadwill** [comment]
Closing this issue as the PR has been merged
